### ISSUE TITLE
error code E404

### ISSUE THREAD

**Issue by getr00t** [zonemeen/musicn#14]
node:14.17.0
npm:6.14.13 
OS:windos10
我看了下说报错E404需要升级npm，我更新了8.10.0也不行
报错如下
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmmirror.com/musicn.js - [NOT_FOUND] musicn.js not found
npm ERR! 404
npm ERR! 404  'musicn.js@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:

**Comment by zonemeen** [comment]
> node:14.17.0 npm:6.14.13 OS:windos10 我看了下说报错E404需要升级npm，我更新了8.10.0也不行 报错如下 npm ERR! code E404 npm ERR! 404 Not Found - GET https://registry.npmmirror.com/musicn.js - [NOT_FOUND] musicn.js not found npm ERR! 404 npm ERR! 404 'musicn.js@latest' is not in the npm registry. npm ERR! 404 You should bug the author to publish it (or use the name yourself!) npm ERR! 404 npm ERR! 404 Note that you can also install from a npm ERR! 404 tarball, folder, http url, or git url.
> 
> npm ERR! A complete log of this run can be found in:

应该要安装 musicn ，不是 musicn.js

**Comment by getr00t** [comment]
> > node:14.17.0 npm:6.14.13 OS:windos10 我看了下说报错E404需要升级npm，我更新了8.10.0也不行 报错如下 npm ERR! code E404 npm ERR! 404 Not Found - GET https://registry.npmmirror.com/musicn.js - [NOT_FOUND] musicn.js not found npm ERR! 404 npm ERR! 404 'musicn.js@latest' is not in the npm registry. npm ERR! 404 You should bug the author to publish it (or use the name yourself!) npm ERR! 404 npm ERR! 404 Note that you can also install from a npm ERR! 404 tarball, folder, http url, or git url.
> > npm ERR! A complete log of this run can be found in:
> 
> 应该要安装 musicn ，不是 musicn.js

哦我下载看的mkd文档直接复制的命令就带有js后缀了。

**Comment by getr00t** [comment]
> > node:14.17.0 npm:6.14.13 OS:windos10 我看了下说报错E404需要升级npm，我更新了8.10.0也不行 报错如下 npm ERR! code E404 npm ERR! 404 Not Found - GET https://registry.npmmirror.com/musicn.js - [NOT_FOUND] musicn.js not found npm ERR! 404 npm ERR! 404 'musicn.js@latest' is not in the npm registry. npm ERR! 404 You should bug the author to publish it (or use the name yourself!) npm ERR! 404 npm ERR! 404 Note that you can also install from a npm ERR! 404 tarball, folder, http url, or git url.
> > npm ERR! A complete log of this run can be found in:
> 
> 应该要安装 musicn ，不是 musicn.js
真是一波三折啊，我这玩意咋跑不起来
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'stream' imported from C:\Users\yongy\AppData\Roaming\npm\node_modules\musicn\lib\download.js
[90m    at packageResolve (internal/modules/esm/resolve.js:655:9)[39m
[90m    at moduleResolve (internal/modules/esm/resolve.js:696:18)[39m
[90m    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)[39m
[90m    at Loader.resolve (internal/modules/esm/loader.js:88:40)[39m
[90m    at Loader.getModuleJob (internal/modules/esm/loader.js:241:28)[39m
[90m    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)[39m
[90m    at link (internal/modules/esm/module_job.js:55:36)[39m {
  code: [32m'ERR_MODULE_NOT_FOUND'[39m

**Comment by zonemeen** [comment]
> 

应该先升级一下node 升到16试试
