### ISSUE TITLE
希望添加其他api，或者添加自定义api功能

### ISSUE THREAD

**Issue by nimade2333** [zonemeen/musicn#19]
如题

**Comment by zonemeen** [comment]
> 如题

你好，你指的添加自定义api意思是添加其他平台的api吗

**Comment by nimade2333** [comment]
> > 如题
> 
> 你好，你指的添加自定义api意思是添加其他平台的api吗

对

**Comment by zonemeen** [comment]
> > > 如题
> > 
> > 
> > 你好，你指的添加自定义api意思是添加其他平台的api吗
> 
> 对

网易云的马上会支持的 其他平台暂时还没
