### ISSUE TITLE
更新到最新版失败

### ISSUE THREAD

**Issue by brucmao** [zonemeen/musicn#21]
有一台电脑还是1.2.6的版本，更新报错

pnpm add -g musicn
 ERROR  Unable to find the global bin directory
Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.

**Comment by zonemeen** [comment]
> 有一台电脑还是1.2.6的版本，更新报错
> 
> pnpm add -g musicn  ERROR  Unable to find the global bin directory Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.

你用npm全局装一下

**Comment by brucmao** [comment]
> > 有一台电脑还是1.2.6的版本，更新报错
> > pnpm add -g musicn  ERROR  Unable to find the global bin directory Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
> 
> 你用npm全局装一下
报错了
npm install musicn -g
npm ERR! code EEXIST
npm ERR! path C:\Users\brucm\scoop\persist\nvm\nodejs\v16.15.0\musicn
npm ERR! EEXIST: file already exists
npm ERR! File exists: C:\Users\brucm\scoop\persist\nvm\nodejs\v16.15.0\musicn
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\brucm\AppData\Local\npm-cache\_logs\2022-06-27T09_42_35_363Z-debug-0.log

**Comment by brucmao** [comment]
加上 --force  成功了
