### ISSUE TITLE
基础的咪咕服务有问题

### ISSUE THREAD

**Issue by BRIDGEa2000** [zonemeen/musicn#23]
![image](https://user-images.githubusercontent.com/82192546/178425060-05e8b7eb-778f-49ab-9e57-aa03e140fe0e.png)

**Comment by zonemeen** [comment]
你好，我自己电脑上边是好的，你上咪咕音乐官网看看能搜索歌曲吗

**Comment by BRIDGEa2000** [comment]
你好，在官网搜索并没有问题。我之前是有全局下载过，今天重装了一下这个包，然后发现咪咕的服务搜不到，

**Comment by BRIDGEa2000** [comment]
你好，在官网搜索并没有问题。我之前是有全局下载过，今天重装了一下这个包，然后发现咪咕的服务搜不到，

**Comment by zonemeen** [comment]
下载的是哪个版本的

**Comment by BRIDGEa2000** [comment]
最新的1.3.18

**Comment by zonemeen** [comment]
你有装什么翻墙工具吗 我猜有可能是被屏蔽了 你电脑请求访问咪咕的地址的时候

**Comment by BRIDGEa2000** [comment]
现在可以了，挺奇怪的。我试了一下挂代理和没挂代理的区别，都可以返回数据。

**Comment by BRIDGEa2000** [comment]
最开始并没有开代理，挺神奇的哈哈哈，可能用的时候恰巧接口有问题吧。
