### ISSUE TITLE
请问，突然报错是为什么？

### ISSUE THREAD

**Issue by YangShaoLong1984** [zonemeen/musicn#24]
![image](https://user-images.githubusercontent.com/66057615/180359994-bd4cdb26-5a3f-4da9-b126-a854e608c274.png)

**Comment by tjj006** [comment]
估计被封了，我也报了这个：Invalid URL

**Comment by zonemeen** [comment]
下载的链接被封了，我试试能不能换个链接

**Comment by zonemeen** [comment]
接口已更新，但现在很多歌都下不了了😅，后面有空会摸索其余哪个平台可以下载无损格式的
