### ISSUE TITLE
更新到新版，不能用了。。。

### ISSUE THREAD

**Issue by sheatming** [zonemeen/musicn#25]
<img width="761" alt="image" src="https://user-images.githubusercontent.com/17745365/181176610-0a89af36-54e0-49c7-98d6-c93df6c97f49.png">

**Comment by zonemeen** [comment]
我的是正常的，版本也是1.3.29，你电脑上面有开什么代理吗？或者你试试网易云的有没有用 `msc 千里之外 -s netease`

**Comment by sheatming** [comment]
> 我的是正常的，版本也是1.3.29，你电脑上面有开什么代理吗？或者你试试网易云的有没有用 `msc 千里之外 -s netease`

网易的可以，默认的不行。代理没有开

**Comment by zonemeen** [comment]
现在还是不行吗

**Comment by sheatming** [comment]
> 

是的 现在还是不行

**Comment by sheatming** [comment]
<img width="770" alt="image" src="https://user-images.githubusercontent.com/17745365/181877254-d58140f4-36d1-4477-80da-04640b09b1a5.png">

**Comment by zonemeen** [comment]
你好，你试试这两个地址输入到浏览器有返回正常的结果吗：https://search.kuwo.cn/r.s?client=kt&all=%E5%8D%83%E9%87%8C%E4%B9%8B%E5%A4%96&pn=0&rn=10&vipver=1&ft=music&encoding=utf8&rformat=json&mobi=1

https://www.kuwo.cn/api/v1/www/music/playUrl?mid=138810&type=1

都是搜索千里之外这首歌的结果

**Comment by zonemeen** [comment]
还有就是你nodejs版本是多少的

**Comment by zonemeen** [comment]
还有就是你nodejs版本是多少的

**Comment by sheatming** [comment]
> 还有就是你nodejs版本是多少的，`replaceAll`是nodejs14.0才支持的，所以电脑里边的node版本要高于14

14.15.0

**Comment by zonemeen** [comment]
你切换更高的版本看看，比如16以上的，我windows和mac os 系统都复现不了，node版本是16以上的
