### ISSUE TITLE
这是链接失效了吗

### ISSUE THREAD

**Issue by wayeh** [zonemeen/musicn#26]
![image](https://user-images.githubusercontent.com/57169828/182124588-955528b1-2c50-4190-b946-2cb178c06938.png)

**Comment by zonemeen** [comment]
你好，我测了下是正常的，你的版本是多少的？

**Comment by wayeh** [comment]
你好，代码是拉的最新的，node版本是14.16.1

**Comment by wayeh** [comment]
> 你好，我测了下是正常的，你的版本是多少的？
你好，代码是拉的最新的，node版本是14.16.1

**Comment by wayeh** [comment]
> 你好，我测了下是正常的，你的版本是多少的？

你好，node版本是14.16.1

**Comment by wayeh** [comment]
node切换到16的版本可以了

**Comment by zonemeen** [comment]
好的，那我把issue关咯
