### ISSUE TITLE
连接不上

### ISSUE THREAD

**Issue by xuyuelin88117** [zonemeen/musicn#28]
![image](https://user-images.githubusercontent.com/91960351/184301043-3d42fb67-cb8e-407f-9e01-debce966c53c.png)
这个报错好几天了，是因为不在大陆吗？
 msc -V
1.4.3
node -v
v16.16.0

**Comment by zonemeen** [comment]
你好，是每次都不行吗？你试下搜索这个链接有返回正常吗：https://search.kuwo.cn/r.s?client=kt&all=%E5%91%A8%E6%9D%B0%E4%BC%A6&pn=0&rn=10&vipver=1&ft=music&encoding=utf8&rformat=json&mobi=1

**Comment by xuyuelin88117** [comment]
https://search.kuwo.cn/rs?client=kt&all=%E5%91%A8%E6%9D%B0 %E4%BC%A6&pn=0&rn=10&vipver=1&ft=音乐&encoding=utf8&rformat=json&mobi=1
[1] 69
[2] 70
[3] 71
-bash: https://search.kuwo.cn/rs?client=kt: No such file or directory
[4] 72
[5] 73
[6] 74
[7] 75
[8] 76
[1]   Exit 127                https://search.kuwo.cn/rs?client=kt
[3]   Done                    pn=0
[4]   Done                    rn=10
[5]   Done                    vipver=1
[6]   Done                    ft=音乐
[7]-  Done                    encoding=utf8
~$ %E4%BC%A6: command not found

**Comment by zonemeen** [comment]
不好意思我描述错了😂，应该是你电脑的浏览器访问一下这个地址，看看有没有返回正常的json

**Comment by xuyuelin88117** [comment]
![image](https://user-images.githubusercontent.com/91960351/184611882-f0175383-4718-4789-b272-17fa848e89d8.png)

**Comment by zonemeen** [comment]
这有返回结果呀，那就不是网络的原因，你再试试网易云的服务有用吗： `msc 周杰伦 -s netease`

**Comment by xuyuelin88117** [comment]
![image](https://user-images.githubusercontent.com/91960351/184634593-05d66bff-dfbb-4b78-8289-8280ea421181.png)

**Comment by zonemeen** [comment]
那估计你是用不了了😂，国内都OK的

**Comment by xuyuelin88117** [comment]
谢谢！
