### ISSUE TITLE
同时下载全部音乐会自动结束（未下载结束）

### ISSUE THREAD

**Issue by seawave0564** [zonemeen/musicn#42]
![image](https://user-images.githubusercontent.com/73242157/204996775-84705c3e-c233-444d-a132-bfd087812bf4.png)

**Comment by zonemeen** [comment]
你好，你这是在哪个os的？我在windows里边是没问题的

**Comment by seawave0564** [comment]
arch amd64 linux5.15 node17
![image](https://user-images.githubusercontent.com/73242157/205007067-df92c398-a76e-40d2-bca1-53328f343544.png)

**Comment by zonemeen** [comment]
我只测了windows和mac os的，linux之前也有人发issue有点问题，我有空的时候自己再测测修修看；对了你下的musicn 版本是多少来着的

**Comment by seawave0564** [comment]
最新的版本1.4.20   辛苦了
