### ISSUE TITLE
歌曲太长的（特殊字符）下不了，可以修复吗？

### ISSUE THREAD

**Issue by gmicroul** [zonemeen/musicn#43]

**Comment by zonemeen** [comment]
你好，有报错的截图吗

**Comment by gmicroul** [comment]
> 你好，有报错的截图吗
看看这个，自动跳了出来

msc level! dapper                           ? 选择歌曲 11. Dapper Dans - "Grim Grinning     Ghosts" - Singing Busts(From "The Haunted
Mansion"/Soundtrack Version).mp3 - 2.81 MB
下载开始...

**Comment by zonemeen** [comment]
确实是会跳出来，我修一下

**Comment by gmicroul** [comment]
> > 你好，有报错的截图吗
> > 看看这个，自动跳了出来
> 
> msc level! dapper ? 选择歌曲 11. Dapper Dans - "Grim Grinning Ghosts" - Singing Busts(From "The Haunted Mansion"/Soundtrack Version).mp3 - 2.81 MB 下载开始...

是不是有特殊字符的原因，而不是长度？

**Comment by gmicroul** [comment]
能编译成一个可执行文件吗？它可以在termux下面安装运行，如果是独立的可执行文件就更好。

**Comment by zonemeen** [comment]
> 能编译成一个可执行文件吗？它可以在termux下面安装运行，如果是独立的可执行文件就更好。

这个的话等得后边有空的时候加一下

**Comment by gmicroul** [comment]
> > 能编译成一个可执行文件吗？它可以在termux下面安装运行，如果是独立的可执行文件就更好。
> 
> 这个的话等得后边有空的时候加一下

好的，这样安卓手机用起来就更加方便了。再也不需要安装一堆有广告有后台的APP了。

**Comment by zonemeen** [comment]
特殊字符存在导致的问题修复了，你可以安装个最新版本

**Comment by gmicroul** [comment]
msc level! dapper
? 选择歌曲 11. Dapper Dans - "Grim Grinning
Ghosts" - Singing Busts(From "The Haunted
Mansion"Soundtrack Version).mp3 - 2.81 MB
下载开始...
[##############################] |~/.../music/t
~/.../music/termux $ msc -v
musicn/1.4.23 android-arm64 node-v18.12.1
~/.../music/termux $

**Comment by gmicroul** [comment]
还不行

**Comment by gmicroul** [comment]
msc level! dapper                           ? 选择歌曲 11. Dapper Dans - "Grim Grinning
Ghosts" - Singing Busts(From "The Haunted
Mansion"Soundtrack Version).mp3 - 2.81 MB
下载开始...
[##############################] |
下载完成，成功 1 首，失败 0 首
~ $ cd storage/music/termux/
~/.../music/termux $ msc level! dapper
? 选择歌曲 11. Dapper Dans - "Grim Grinning
Ghosts" - Singing Busts(From "The Haunted
Mansion"Soundtrack Version).mp3 - 2.81 MB
下载开始...
~/.../music/termux $

在home目录可以，其他目录不行

**Comment by gmicroul** [comment]
~ $ msc level! dapper                           ? 选择歌曲 11. Dapper Dans - "Grim Grinning
Ghosts" - Singing Busts(From "The Haunted
Mansion"Soundtrack Version).mp3 - 2.81 MB
下载开始...
[##############################] |
下载完成，成功 1 首，失败 0 首
~ $ cd storage/music/termux/
~/.../music/termux $ msc level! dapper
? 选择歌曲 11. Dapper Dans - "Grim Grinning
Ghosts" - Singing Busts(From "The Haunted
Mansion"Soundtrack Version).mp3 - 2.81 MB
下载开始...
~/.../music/termux $ msc level! dapper
? 选择歌曲 10. Peter Thomas Sound Orchester -
Snappy Dapper.mp3 - 3 MB
下载开始...
[##############################] |
下载完成，成功 1 首，失败 0 首
~/.../music/termux $

下其它的可以

**Comment by zonemeen** [comment]
😵 这个还是由于特殊符号存在导致的，我昨天用的mbp苹果系统验证是可以的，猜测是node的一些跨平台行为有点点不一样；我更新了一下最新版本了，你验证一下

**Comment by gmicroul** [comment]
> 

可以下载了，很不错，辛苦了
