### ISSUE TITLE
用 yarn 下载后用不了

### ISSUE THREAD

**Issue by yenche123** [zonemeen/musicn#5]
提示 
```
'musicn' 不是内部或外部命令，也不是可运行的程序
```
然后 npm 就可以

![image](https://user-images.githubusercontent.com/28533125/168277670-b8f80dbc-112a-4646-bdaf-57a04538a1b8.png)

![image](https://user-images.githubusercontent.com/28533125/168277911-ce1a07e2-a713-4e0a-9620-5ed019aeac45.png)

node: 14.17.3
windows 11

**Comment by zonemeen** [comment]
> 

你好，我公司里边也是windows是ok的，报这种错的话你得自己手动去添加环境变量了
