### ISSUE TITLE
求教命令行模式下如何翻页

### ISSUE THREAD

**Issue by wy580477** [zonemeen/musicn#50]
版本： v1.4.41
环境： windows 10 powershell Node.js v19.9.0，node:alpine 容器，node:bullseye-slim 容器

![image](https://user-images.githubusercontent.com/98247050/231029083-01fddbd9-4891-4aaf-ad72-6a7ae871230c.png)

上下左右方向键和pagedown/pageup都试过了，实在不知道怎么翻页

**Comment by zonemeen** [comment]
你好 @wy580477，命令行模式暂时不支持翻页的，因为Inquirer.js这个库暂时还没提供这样的交互，你想翻页下载的话可以`msc -q` 开启网页模式去翻页进行下载

**Comment by wy580477** [comment]
> 你好 @wy580477，命令行模式暂时不支持翻页的，因为Inquirer.js这个库暂时还没提供这样的交互，你想翻页下载的话可以`msc -q` 开启网页模式去翻页进行下载

感谢回答。再请问一下，既然不能翻页，那 "-n" 这个参数指定的页码数，具体是什么作用。

**Comment by zonemeen** [comment]
最开始就是为了手动输入翻页用的😂后边加了网页功能后可以用在网页上的翻页

**Comment by wy580477** [comment]
> 最开始就是为了手动输入翻页用的😂后边加了网页功能后可以用在网页上的翻页

感谢，我理解错误了，以为是指定一共多少页，原来是指定哪一页。
