### ISSUE TITLE
无法通过歌单下载

### ISSUE THREAD

**Issue by linkoln** [zonemeen/musicn#51]
F:\Songs>msc --songListId 7225790720
✖ 没搜索到歌单ID: 7225790720 的相关结果

**Comment by zonemeen** [comment]
你好，应该是这个id的咪咕歌单不存在

![image](https://github.com/zonemeen/musicn/assets/44596995/c8d0cb08-04ff-4798-a900-a652e63ed076)

**Comment by linkoln** [comment]
您好，您发来的邮件我已经收到，我会尽快阅读

**Comment by linkoln** [comment]
噢，是不支持网易云歌单是吧？

**Comment by linkoln** [comment]
。。
