### ISSUE TITLE
出现连接超时下载失败的问题

### ISSUE THREAD

**Issue by NicPants** [zonemeen/musicn#52]
我在自己的电脑和阿里云服务器上尝试下载不同的歌曲均失败，因为我人在国外所以我感觉应该不是因为墙的原因吧。
报错信息如下：
![1](https://github.com/zonemeen/musicn/assets/71953489/a84ebc01-ca01-431b-ae58-2b34f8489b35)
这是阿里云服务器上的报错，尝试直接ping这个IP地址是通的。
<img width="557" alt="2" src="https://github.com/zonemeen/musicn/assets/71953489/838a1d8b-518c-42d0-9b10-d7570fb16816">
这是我自己电脑上的报错。
各位有没有什么头绪？挠头.jpg

**Comment by zonemeen** [comment]
你好，是所有歌曲都下载不了吗

**Comment by NicPants** [comment]
> 你好，是所有歌曲都下载不了吗

这我不太能确定，我只试了七八首，我看到主页说无损格式和普通mp3格式可能是不同的源也尝试下载不同格式的，但是无一例外都失败

**Comment by zonemeen** [comment]
应该是你在国外的原因，之前也有身在海外的小伙伴发过issue说下载不了的

**Comment by NicPants** [comment]
> 应该是你在国外的原因，之前也有身在海外的小伙伴发过issue说下载不了的

我也想到过这个问题，所以在阿里云的服务器上也试了试，服务器地址在杭州但是也没成功过。

**Comment by zonemeen** [comment]
你再都试一下这个地址可以访问吗，https://freetyst.nf.migu.cn/public/product9th/product46/2023/02/1417/2009%E5%B9%B406%E6%9C%8826%E6%97%A5%E5%8D%9A%E5%B0%94%E6%99%AE%E6%96%AF/%E6%A0%87%E6%B8%85%E9%AB%98%E6%B8%85/MP3_320_16_Stero/60054701923171750.mp3，周杰伦-晴天 的在线地址，有时间的话我去云服务器试试

**Comment by NicPants** [comment]
> 你再都试一下这个地址可以访问吗，https://freetyst.nf.migu.cn/public/product9th/product46/2023/02/1417/2009%E5%B9%B406%E6%9C%8826%E6%97%A5%E5%8D%9A%E5%B0%94%E6%99%AE%E6%96%AF/%E6%A0%87%E6%B8%85%E9%AB%98%E6%B8%85/MP3_320_16_Stero/60054701923171750.mp3 周杰伦-晴天 的在线地址，有时间的话我去云服务器试试

在我本地直连、挂梯子都试过了，都是404，在阿里云服务器上也是404。

**Comment by NicPants** [comment]
> > 你再都试一下这个地址可以访问吗，https://freetyst.nf.migu.cn/public/product9th/product46/2023/02/1417/2009%E5%B9%B406%E6%9C%8826%E6%97%A5%E5%8D%9A%E5%B0%94%E6%99%AE%E6%96%AF/%E6%A0%87%E6%B8%85%E9%AB%98%E6%B8%85/MP3_320_16_Stero/60054701923171750.mp3 周杰伦-晴天 的在线地址，有时间的话我去云服务器试试
> 
> 在我本地直连、挂梯子都试过了，都是404，在阿里云服务器上也是404。

更新，这会儿又可以打开了，本地和云服务器都可以。。很迷惑

**Comment by zonemeen** [comment]
可以就行，是不是之前你用的老版本的

**Comment by NicPants** [comment]
> 可以就行，是不是之前你用的老版本的，还有我把打包命令精简改回成build了

刚刚用的版本一直是1.4.46，版本没变但是就之前不行然后突然好了，搞不懂问题出在哪。

**Comment by zonemeen** [comment]
可能是梯子或者网络的问题吧😂
