### ISSUE TITLE
下载失败 报错信息为空

### ISSUE THREAD

**Issue by zzpop** [zonemeen/musicn#53]
PS C:\Users\Administrator\AppData\Roaming\npm\node_modules\musicn> msc 黄丽玲 -n 2
? 选择歌曲 2. 难得孤寂 - A-Lin.flac - 52.1 MB, 4. 一直走 - A-Lin.flac - 45.1 MB, 5. 画心(歌手2019) - 杨坤,A-Lin.flac -
54.5 MB, 6. 我不离开 - 戴爱玲,A-Lin.flac - 60 MB, 7. 雨后彩虹 - A-Lin.flac - 42.3 MB, 8. 抱歉 我不抱歉
(电影《恋爱好好说》主题曲)(The movie theme song of Love Talk) - A-Lin.flac - 28.3 MB, 9. 听见下雨的声音 (Live) -
12. 真相-电视剧《守护神之保险调查》主题曲 - A-Lin.flac - 45.5 MB, 13. 我笑到都哭了 - A-Lin.flac - 44 MB, 14. 我都记得
(电影《奇人密码：古罗布之谜》主题曲) - A-Lin.flac - 55.5 MB, 15. 最佳男主角 - A-Lin.flac - 67.1 MB, 16. Gentlewoman -
A-Lin.flac - 47.4 MB, 17. 我值得 - A-Lin.flac - 49.6 MB, 18. 梦话 (电视剧《幻城》片尾曲) - A-Lin.flac - 47.1 MB, 19.
海洋之心 (A Lin Version)(电影《海洋奇缘》主题曲) - A-Lin.flac - 35.9 MB
下载开始...
[##############################] | 难得孤寂 - A-Lin.flac | 52.1 MB/52.1 MB
[##############################] | 一直走 - A-Lin.flac | 45.1 MB/45.1 MB
[##############################] | 画心(歌手2019) - 杨坤,A-Lin.flac | 54.5 MB/54.5 MB
[##############################] | 我不离开 - 戴爱玲,A-Lin.flac | 60 MB/60 MB
[##############################] | 雨后彩虹 - A-Lin.flac | 42.3 MB/42.3 MB
[##############################] | 抱歉 我不抱歉 (电影《恋爱好好说》主题曲)(The movie theme song of Love Talk) - A-Lin.flac
[##############################] | 听见下雨的声音 (Live) - A-Lin.flac | 50.9 MB/50.9 MB
[##############################] | 讨厌(蒙面唱将猜猜猜) - A-Lin.flac | 53.6 MB/53.6 MB
[##############################] | 伤痕(蒙面唱将猜猜猜) - A-Lin.flac | 48.7 MB/48.7 MB
[##############################] | 真相-电视剧《守护神之保险调查》主题曲 - A-Lin.flac | 45.5 MB/45.5 MB
[##############################] | 我笑到都哭了 - A-Lin.flac | 44 MB/44 MB
[##############################] | 我都记得 (电影《奇人密码：古罗布之谜》主题曲) - A-Lin.flac | 55.5 MB/55.5 MB
[##############################] | 最佳男主角 - A-Lin.flac | 67.1 MB/67.1 MB
[##############################] | Gentlewoman - A-Lin.flac | 47.4 MB/47.4 MB
[##############################] | 我值得 - A-Lin.flac | 49.6 MB/49.6 MB
[##############################] | 梦话 (电视剧《幻城》片尾曲) - A-Lin.flac | 47.1 MB/47.1 MB
[##############################] | 海洋之心 (A Lin Version)(电影《海洋奇缘》主题曲) - A-Lin.flac | 35.9 MB/35.9 MB
下载完成，成功 14 首，失败 3 首
失败信息：
1.我不离开 - 戴爱玲,A-Lin.flac下载失败，报错信息：
2.最佳男主角 - A-Lin.flac下载失败，报错信息：
3.我值得 - A-Lin.flac下载失败，报错信息：
PS C:\Users\Administrator\AppData\Roaming\npm\node_modules\musicn> msc 黄丽玲 -n 2
? 选择歌曲 6. 我不离开 - 戴爱玲,A-Lin.flac - 60 MB, 15. 最佳男主角 - A-Lin.flac - 67.1 MB, 17. 我值得 - A-Lin.flac -
49.6 MB
下载开始...
[##############################] | 我不离开 - 戴爱玲,A-Lin.flac | 60 MB/60 MB
[##############################] | 最佳男主角 - A-Lin.flac | 67.1 MB/67.1 MB
[##############################] | 我值得 - A-Lin.flac | 49.6 MB/49.6 MB
下载完成，成功 3 首，失败 0 首

**Comment by zonemeen** [comment]
你好，我用同样的命令试了一下是可以成功下载的，估计这种是网络或者梯子？导致的偶发性问题

**Comment by zzpop** [comment]
是的，是偶发性问题，是我没说清楚
