### ISSUE TITLE
建议：当采用WEB方式搜索时，能把文件存到服务器上

### ISSUE THREAD

**Issue by HongKing** [zonemeen/musicn#62]
当采用WEB方式搜索时，点击下载按钮能把文件存到运行服务器上。
应用场景：musicn + navdriome使用时，目前下载音乐后还要再手动上传上去
期望效果：musicn 配置data目录（与navdriome的音乐文件目录一致），当再musicn中搜索到歌曲后，点击下载能下载到data目录中，这样navdriome就能自动扫描到了

**Comment by zonemeen** [comment]
目前 musicn 是支持自定义下载路径的，你指定成navdriome的音乐下载文件目录即可

**Comment by HongKing** [comment]
是的，用命令行能达到这个效果，只是用命令行没有WEB方便

**Comment by caton-hpg** [comment]
我也是需要这个功能

**Comment by lovefan-fan** [comment]
不会node，用python写了个接口，然后修改了下index.htlm。增加了个下载按钮，可以下载到服务器了

**Comment by caton-hpg** [comment]
> 不会node，用python写了个接口，然后修改了下index.htlm。增加了个下载按钮，可以下载到服务器了

有pr吗？

**Comment by zonemeen** [comment]
最新版可以支持这种下载形式了，详情可以查看最新的文档🚀

**Comment by go1em** [comment]
请问是怎么通过web下载到服务器上呢，试了一晚上也不行，求指导，谢谢
