### ISSUE TITLE
能否提供按歌手下载、热歌榜单、歌单等功能？？

### ISSUE THREAD

**Issue by Wangzhe00** [zonemeen/musicn#8]
说白了就是大佬还知道其他api么，自己又试不出来:(

**Comment by Wangzhe00** [comment]
要是知道的话，嫌麻烦不用实现，只需comment下即可，ths

**Comment by zonemeen** [comment]
> 要是知道的话，嫌麻烦不用实现，只需comment下即可，ths

现有的这个下载api还是无意中发现的 你说的类似功能接口暂时我也不知道呢 后边可以再摸索一下 还有昂 我不是什么大佬哈 就一前端爱好者 可以喊我项目作者🤣
